### ISSUE TITLE
Link to the video is broken

### ISSUE THREAD

**Issue by O-Hahn** [ibm-cloud-docs/visual-recognition#112]
Try to use the grafical inteface from watson studio to train an custom visual recognition service - the link in the documentation is broken.
Also since the new Cloud Pack for Data interface - the integration of watson services is wrong. As mentioned in the documentation later (Watson studio integration) - leads to an old video based on 2018 - which is really confusing because you will not find any gui like that.

**Comment by SirSpidey** [comment]
@O-Hahn Thanks for the report. The video is embedded in the Watson Studio (also referred to as Cloud Pak for Data) [documentation](https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/visual-recognition-create-model.html?audience=wdp&context=cpdaas) and available directly at https://video.ibm.com/channel/23952663/video/ws-vr-create-model. 

We'll update the docs with the new link.

**Comment by SirSpidey** [comment]
> Also since the new Cloud Pack for Data interface - the integration of watson services is wrong. As mentioned in the documentation later (Watson studio integration) - leads to an old video based on 2018 - which is really confusing because you will not find any gui like that.

I'm sorry that the older UI that the video demonstrates is not helpful. I'll let the team know that the video needs an update. I hope that the documentation is more helpful.
