### ISSUE TITLE
Alternative to visual recognition?

### ISSUE THREAD

**Issue by kurai021** [ibm-cloud-docs/visual-recognition#113]
Will the IBM Watson team prepare an alternative to the Visual Recognition API in the same way that an alternative to the Personality Insights API is proposed? From my point of view, it is a great tool for developers and designers who do not have great experience in machine learning or who find it difficult to train a tool to fulfill this task

**Comment by SirSpidey** [comment]
Hi @kurai021. I agree that VisRec is an easy to understand introduction to ML. 

One alternative is [Maximo Visual Inspection](https://www.ibm.com/products/ibm-maximo-visual-inspection), although this is an on-premises solution. Additionally, take a look at [Watson Machine Learning](https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/ml-overview.html). You can train open-source computer vision models with WML.

If you have any other comments or questions, I can pass them along.
